site_name: Freely Given Harmonic Church
site_description: "Heal the sick, cleanse the lepers, raise the dead, cast out demons. Freely you have received, freely give."
site_author: null

site_url: https://freelygivenharmonic.github.io
repo_url: https://github.com/FreelyGivenHarmonicChurch/FreelyGivenHarmonicChurch.github.io
edit_uri: edit/main/docs/

nav:
    - Music:
        - Original:
            - Son of Man: 'music/original/son_of_man.md'
        - Taize: 'music/taize.md'
    - Worship:
        - Prayers: 'worship/prayers.md'
        - Texts: 'worship/texts.md'
    - Wisdom:
        - Quotations:
            - Love: 'wisdom/quotations/love.md'
            - Nonviolence: 'wisdom/quotations/nonviolence.md'
            - Simplicity: 'wisdom/quotations/simplicity.md'
            - Pluralism: 'wisdom/quotations/pluralism.md'
            - Reason: 'wisdom/quotations/reason.md'
            - Action: 'wisdom/quotations/action.md'
            - Nature: 'wisdom/quotations/nature.md'
            - Mindfulness: 'wisdom/quotations/mindfulness.md'
        - Teachers: 'wisdom/teachers/teachers.md'
        - Worldviews:
            - Mysticism: 'wisdom/worldviews/mysticism.md'
            - Christian Anarchism: 'wisdom/worldviews/christian_anarchism.md'
            - Deep Ecology: 'wisdom/worldviews/deep_ecology.md'

theme:
  name: readthedocs

plugins: []
