site_name: Freely Given Harmonic Church
site_description: null
site_author: null

site_url: https://freelygivenharmonic.church
repo_url: https://github.com/FreelyGivenHarmonicChurch/FreelyGivenHarmonicChurch.github.io
edit_uri: edit/main/docs/

nav:
    - Music:
        - Taize: 'music/taize.md'
    - Wisdom:
        - Foundations:
            - Interconnectedness: 'wisdom/foundations/interconnectedness.md'
            - Love: 'wisdom/foundations/love.md'
            - Nature: 'wisdom/foundations/nature.md'
            - Community: 'wisdom/foundations/community.md'
            - Nonviolence: 'wisdom/foundations/nonviolence.md'
            - Rejecting Mammon: 'wisdom/foundations/rejecting_mammon.md'
            - Pluralism: 'wisdom/foundations/pluralism.md'
            - Reason: 'wisdom/foundations/reason.md'
            - Works: 'wisdom/foundations/works.md'
        - Teachers: 'wisdom/teachers.md'
    - Worship:
        - Prayers: 'worship/prayers.md'
        - Texts: 'worship/texts.md'

theme:
  name: readthedocs

plugins: []
