site_name: Freely Given Harmonic Church
site_description: "Heal the sick, cleanse the lepers, raise the dead, cast out demons. Freely you have received, freely give."
site_author: null

site_url: https://freelygivenharmonic.github.io
repo_url: https://github.com/FreelyGivenHarmonicChurch/FreelyGivenHarmonicChurch.github.io
edit_uri: edit/main/docs/

nav:
    - Music:
        - Original:
            - Son of Man: 'music/original/son_of_man.md'
        # - Protest:
        #     - Overview: 'music/protest/overview.md'
        # - Sacred:
        #     - Overview: 'music/sacred/overview.md'        
        #     - Taize: 'music/sacred/taize.md'
    - Practice:
        - Recitations:
            - Chants: 'practice/recitations/chants.md'
            - Prayers: 'practice/recitations/prayers.md'
        - Texts: 'practice/texts.md'
    - Wisdom:
        - Quotations:
            - Reason: 'wisdom/quotations/reason.md'
            - Action: 'wisdom/quotations/action.md'
        - Teachers: 'wisdom/teachers/teachers.md'
        - Ideas:
            - Experience:
                - Religious Experience: 'wisdom/ideas/experience/religious_experience.md'
                - Mysticism: 'wisdom/ideas/experience/mysticism.md'
                - Mindfulness: 'wisdom/ideas/experience/mindfulness.md'
                - Quotes: 'wisdom/ideas/experience/quotes.md'
            - Diversity:
                - Pluralism: 'wisdom/ideas/diversity/pluralism.md'
                - Perennialism: 'wisdom/ideas/diversity/perennialism.md'
                - Double Belonging: 'wisdom/ideas/diversity/double_belonging.md'
                - Quotes: 'wisdom/ideas/diversity/quotes.md'
            #     - Interreligious(sic?) Dialogue: ''
            - Love:
                - Quotes: 'wisdom/ideas/love/quotes.md'
            - Community:
                - Quotes: 'wisdom/ideas/community/quotes.md'
            - Nature:
                - Environmentalism: 'wisdom/ideas/nature/environmentalism.md'
                - Deep Ecology: 'wisdom/ideas/nature/deep_ecology.md'
                - Quotes: 'wisdom/ideas/nature/quotes.md'
            - Simplicity:
                - Quotes: 'wisdom/ideas/simplicity/quotes.md'
                # - Gift Economy/Economy of Abundance
            - Pacifism:
                - Overview: 'wisdom/ideas/pacifism/overview.md'
                - Quotes: 'wisdom/ideas/pacifism/quotes.md'
            - Anarchism: 
                - Overview: 'wisdom/ideas/anarchism/overview.md'
                - Anarcho-pacifism: 'wisdom/ideas/anarchism/anarcho-pacifism.md'
                - Christian Anarchism: 'wisdom/ideas/anarchism/christian_anarchism.md'

theme:
  name: readthedocs

plugins:
    - search
