site_name: Freely Given Harmonic Church
site_description: Freely you have received; freely give.
site_author: null

site_url: https://freelygivenharmonic.church
repo_url: https://github.com/FreelyGivenHarmonicChurch/FreelyGivenHarmonicChurch.github.io
edit_uri: edit/main/docs/

nav:
    - Wisdom:
        - Love: 'wisdom/love.md'
        - Nonviolence: 'wisdom/nonviolence.md'
        - Simplicity: 'wisdom/simplicity.md'
        - Pluralism: 'wisdom/pluralism.md'
        - Reason: 'wisdom/reason.md'
        - Action: 'wisdom/action.md'
        - Nature: 'wisdom/nature.md'
        - Mindfulness: 'wisdom/mindfulness.md'
        - Teachers: 'wisdom/teachers.md'
    - Worship:
        - Prayers: 'worship/prayers.md'
        - Texts: 'worship/texts.md'
    - Music:
        - Taize: 'music/taize.md'

theme:
  name: readthedocs

plugins: []
