site_name: Freely Given Harmonic Church
site_description: "Heal the sick, cleanse the lepers, raise the dead, cast out demons. Freely you have received, freely give."
site_author: null

site_url: https://freelygivenharmonic.github.io
repo_url: https://github.com/FreelyGivenHarmonicChurch/FreelyGivenHarmonicChurch.github.io
edit_uri: edit/main/docs/

nav:
    - Music:
        - Original:
            - Son of Man: 'music/original/son_of_man.md'
        # - Protest:
        #     - Overview: 'music/protest/overview.md'
        # - Sacred:
        #     - Overview: 'music/sacred/overview.md'        
        #     - Taize: 'music/sacred/taize.md'
    - Practice:
        - Recitations:
            - Chants: 'practice/recitations/chants.md'
            - Prayers: 'practice/recitations/prayers.md'
        - Texts: 'practice/texts.md'
    - Wisdom:
        - Quotations:
            - Love: 'wisdom/quotations/love.md'
            - Nonviolence: 'wisdom/quotations/nonviolence.md'
            - Simplicity: 'wisdom/quotations/simplicity.md'
            - Pluralism: 'wisdom/quotations/pluralism.md'
            - Reason: 'wisdom/quotations/reason.md'
            - Action: 'wisdom/quotations/action.md'
            - Nature: 'wisdom/quotations/nature.md'
            - Mindfulness: 'wisdom/quotations/mindfulness.md'
        - Teachers: 'wisdom/teachers/teachers.md'
        - Ideas:
            - Experience:
                - Religious Experience: 'wisdom/ideas/experience/religious_experience.md'
                - Mysticism: 'wisdom/ideas/experience/mysticism.md'
            - Diversity:
            #     - Overview: 'test'
                - Pluralism: 'wisdom/ideas/diversity/pluralism.md'
                - Perennialism: 'wisdom/ideas/diversity/perennialism.md'
                - Double Belonging: 'wisdom/ideas/diversity/double_belonging.md'
            #     - Interreligious(sic?) Dialogue: ''
            - Pacifism:
                - Overview: 'wisdom/ideas/pacifism/overview.md'
            - Anarchism: 
                - Overview: 'wisdom/ideas/anarchism/overview.md'
                - Anarcho-pacifism: 'wisdom/ideas/anarchism/anarcho-pacifism.md'
                - Christian Anarchism: 'wisdom/ideas/anarchism/christian_anarchism.md'
            # - Gift Economy/Economy of Abundance
            # - Love
            # - Community
            - Environmentalism:
                - Overview: 'wisdom/ideas/environmentalism/overview.md'
                - Deep Ecology: 'wisdom/ideas/environmentalism/deep_ecology.md'
            

theme:
  name: readthedocs

plugins:
    - search
